// Azure Resource Graph Query
// Find all VMs in "NonCompliant" state with Azure Policies
PolicyResources
| where type =~ 'microsoft.policyinsights/policystates'
| where properties.complianceState == 'NonCompliant'
| extend vmResourceId = properties.resourceId, vmresourceType = properties.resourceType, PolicyAssignmentName = properties.policyAssignmentName
| where vmresourceType == 'Microsoft.Compute/virtualMachines'
| project recommendationId = "dbw-18", name = tostring(split(tostring(properties.resourceId), '/')[8]), id=vmResourceId, param1 = strcat ("Policyname: ", name)
