// Azure Resource Graph Query
// Find all Premium API Management instances that aren't zone redundant
resources
| where type =~ 'Microsoft.ApiManagement/service'
| extend skuName = sku.name
| where tolower(skuName) == tolower('premium')
| where isnull(zones) or array_length(zones) < 2
| extend zoneValue = iff((isnull(zones)), "null", zones)
| project recommendationId = "apim-2", name, id, param1="Zones: No Zone or Zonal", param2=strcat("Zones value: ", zoneValue )
