// Azure Resource Graph Query
// The query filters the resources based on the type "microsoft.web/serverfarms" i.e. App Service Plans that are not setup to use standard or premium SKUs.
// TODO: Extend this query to show automatic scaling or App level automatic scale 
resources
| where type =~ "microsoft.insights/autoscalesettings"
| where properties.targetResourceUri contains "microsoft.web/serverfarms"
| project AppServicePlan = split(properties.targetResourceUri, '/')[8], ResourceGroup = split(properties.targetResourceUri, '/')[4]
| project AppServicePlan, ResourceGroup