// Azure Resource Graph Query
// This query will display all images that are not using the latest version.
| where type == "microsoft.compute/virtualmachinescalesets"
| extend VMSSName = name
| extend ImageReference = tostring(properties.virtualMachineProfile.storageProfile.imageReference.version)
| where ImageReference != "latest"
| project recommendationId="vmss-10",name,id, param1= ImageReference
