// Azure Resource Graph Query
// Find all Application Gateways without autoscaling configured or less than 2 instances assigned
Resources
| wheretype == "microsoft.network/applicationGateways"
| whereproperties.capacity.autoScaleConfiguration != null
| whereisnull(properties.autoscaleConfiguration) or properties.autoscaleConfiguration.minCapacity <= 2
| project recommendationId="appgw-1",name, id, tags, param1=autoscaleConfiguration, param2=properties

