// Azure Resource Graph Query
//Provides a list of Azure App Service resources and checks if they is any App Setting configured under this App

appserviceresources
| where type == "microsoft.web/sites/config"
| extend AppSettings = iif(isempty(properties.AppSettings), true, false)
| where AppSettings == false
| project  recommendationId="app-6", id, name, tags="", param1="AppSettings is not configured"
