//Configure minimal logging and retention of logs.
//Query to get the list of Log analytics workspaces and their current configured retention period
resources
| where type == "microsoft.operationalinsights/workspaces"
| extend RetentionPeriod = tostring(properties.retentionInDays), SkuName=tostring(properties.sku.name)
| project recommendationId="log-5", name,location,resourceGroup,RetentionPeriod,SkuName,subscriptionId
