// Azure Resource Graph Query
// Returns each AKS cluster with its nodepools and the taints set for each nodepool
resources
| where type == "microsoft.containerservice/managedclusters"
| mv-expand agentPoolProfile = properties.agentPoolProfiles
| extend taint = tostring(parse_json(agentPoolProfile.nodeTaints))
| extend nodePool = tostring(parse_json(agentPoolProfile.name))
| project recommendationid="aks-20", id, name, nodepoolName=nodePool, taint=taint
