// Azure Resource Graph Query
// Returns whether each AKS cluster has Azure Monitor enabled and Container Insights enabled
resources
|  where type == "microsoft.containerservice/managedclusters"
|  extend azureMonitor = tostring (parse_json(properties.azureMonitorProfile.metrics.enabled))
|  extend insights = tostring (parse_json(properties.addonProfiles.omsagent.enabled))
|  project recommendationId="aks-20",id, name, param1=strcat("azureMonitorProfileEnabled: ", azureMonitor), param2=strcat("containerInsightsEnabled: ", insights)
