//under development
//Resources
//| where type == "microsoft.network/applicationGateways"
//| extend appGatewayResourceId = tostring(id)
//| mvexpand probeConfig = properties.probes
//| where probeConfig.probeName != "GatewaySslCertificate"
//| where iif(isnotempty(probeConfig.pickHostName), "Yes", "No")
//| project recommendationId="agw-6",name, id, param1=strcat("appGatewayResourceId: ", appGatewayResourceId), param2=strcat("customHealthProbeUsed :", customHealthProbeUsed)
