// Azure Resource Graph Query
// Find all VMs in "NonCompliant" state with Azure Policies
PolicyResources
| where type =~ "Microsoft.PolicyInsights/policyStates" and properties.resourceType =~ "Microsoft.Compute/virtualMachines" and properties.complianceState =~ "NonCompliant"
| extend vmResourceId = properties.resourceId, PolicyAssignmentName = properties.policyAssignmentName
| project recommendationId = "vm-18", name = tostring(split(tostring(properties.resourceId), '/')[8]), id=vmResourceId, tags, param1 = strcat ("Policyname: ", PolicyAssignmentName)
