// Azure Resource Graph Query
// This resource graph query will return all Key Vaults that does not have a Private Endpoint Connection.
resources
| where type == "microsoft.keyvault/vaults"
| where isnull(properties.privateEndpointConnections) or properties.privateEndpointConnections[0].properties.provisioningState != ("Succeeded")
| project recommendationId = "kv-3", name, id, PrivatelinkEndpoint = "No Private Endpoint"
