// Azure Resource Graph Query
// This resource graph query will return all Key Vaults that does not have a Private Endpoint Connection.
resources
| where type == "microsoft.keyvault/vaults"
| where tostring(properties['privateEndpointConnections'][0]['properties']['provisioningState']) !in ("Succeeded", "Ready", "Pending", "Failed")
| project recommendationId = "kv-3", name, id, location, resourceGroup, subscriptionId, PrivatelinkEndpoint = tostring(properties['privateEndpointConnections'][0]['properties']['provisioningState'])
