// Azure Resource Graph query
// TRAF-1 - Traffic Manager Monitor Status Should be Online 
resources
| where type == "microsoft.network/trafficmanagerprofiles"
| where properties.monitorConfig.profileMonitorStatus !has 'Online'
| project recommendationId="traf-1", name, id, tags, param1 = strcat ("Protocol: ", properties.monitorConfig.protocol), param2 = strcat ("Tolerated number of failures: ", properties.monitorConfig.toleratedNumberOfFailures), param3 = strcat ("Probe timeout(seconds) : " , properties.monitorConfig.timeoutInSeconds)

