// Azure Resource Graph Query
// Find all disks that are not encrypted
Resources
| where type == "microsoft.compute/disks"
| project "vm-19", diskName=name, encryptionType=properties.encryption.type, diskState=properties.diskState
| where encryptionType !in ("EncryptionAtRestWithCustomerKey", "EncryptionAtRestWithPlatformAndCustomerKeys", "EncryptionAtRestWithPlatformKey")
| order by diskName asc
